const { Style } = require('../models');

const styleData = [
  // {
  //   product_name: 'Adidas',
  //   brand_id: 3,
  //   filename: '01-adidas.png',
  //   description: 'Adidas logo',
  // },
  // {
  //   product_name: 'Jordan',
  //   brand_id: 2,
  //   filename: '02-jordan.png',
  //   description: 'Jordan logo',
  // },
  // {
  //   product_name: 'Nike',
  //   brand_id: 1,
  //   filename: '03-nike.png',
  //   description: 'Nike logo',
  // },
  // {
  //   product_name: 'New Balance',
  //   brand_id: 4,
  //   filename: '04-new-balance.png',
  //   description: 'New Balance logo',
  // },
  {
    product_name: 'Adidas shoe',
    brand_id: 3,
    filename: '05-Adidas-Originals-NMD_R1.png',
    price: '$160',
    description: 'Adidas Originals NMD_R1',
    product_description:,
  },
  {
    product_name: 'Adidas shoe',
    brand_id: 3,
    filename: '06-Adidas-Pharrell-Human-Race-Sichona-Burgundy.png',
    price: '$180',
    description: 'Adidas Pharrell x Human Race Sichona "Burgundy"',
    product_description:,
  },
  {
    product_name: 'Adidas shoe',
    brand_id: 3,
    filename: '07-Adidas-Superstar.png',
    price: '$100',
    description: 'Adidas Superstar',
    product_description:,
  },
  {
    product_name: 'Adidas shoe',
    brand_id: 3,
    filename: '08-Adidas-Yeezy-Boost-350-Turtle-Dove.png',
    price: '$200',
    description: 'Adidas Yeezy Boost 350 "Turtle Dove"',
    product_description:,
  },
  {
    product_name: 'Adidas shoe',
    brand_id: 3,
    filename: '09-Adidas-YEEZY-FOAM-RUNNER-Onyx.png',
    price: '$170',
    description: 'Adidas YEEZY FOAM RUNNER "Onyx"',
    product_description:,
  },
  {
    product_name: 'Jordan shoe',
    brand_id: 2,
    filename: '10-Air-Jordan-1-High-85-Georgetown.png',
    price: '$200',
    description: 'Air Jordan 1 High 85 "Georgetown"',
    product_description:,
  },
  {
    product_name: 'Jordan shoe',
    brand_id: 2,
    filename: '11-Air-Jordan-1-Travis-Scott-Low-Reverse-Mocha.png',
    price: '$150',
    description: 'Air Jordan 1 Travis Scott Low "Reverse Mocha"',
    product_description:,
  },
  {
    product_name: 'Jordan shoe',
    brand_id: 2,
    filename: '12-Air-Jordan-4-White-Oreo.png',
    price: '$190',
    description: 'Air Jordan 4 "White Oreo"',
    product_description:,
  },
  {
    product_name: 'Jordan shoe',
    brand_id: 2,
    filename: '13-Air-Jordan-6-UNC.png',
    price: '$210',
    description: 'Air Jordan 6 "UNC"',
    product_description:,
  },
  {
    product_name: 'Jordan shoe',
    brand_id: 2,
    filename: '14-Air-Jordan-12-Playoffs.png',
    price: '$210',
    description: 'Air Jordan 12 "Playoffs"',
    product_description:,
  },
  {
    product_name: 'Nike shoe',
    brand_id: 1,
    filename: '15-Nike-Air-Force-1.png',
    price: '$100',
    description: 'Nike Air Force 1',
    product_description:,
  },
  {
    product_name: 'Nike shoe',
    brand_id: 1,
    filename: '16-Nike-Air-Max-90.png',
    price: '$130',
    description: 'Nike Air Max 90',
    product_description:,
  },
  {
    product_name: 'Nike shoe',
    brand_id: 1,
    filename: '17-Nike-Air-Max-95-SE.png',
    price: '$180',
    description: 'Nike Air Max 95 SE',
    product_description:,
  },
  {
    product_name: 'Nike shoe',
    brand_id: 1,
    filename: '18-Nike-Air-Max-97.png',
    price: '$170',
    description: 'Nike Air Max 97',
    product_description:,
  },
  {
    product_name: 'Nike shoe',
    brand_id: 1,
    filename: '19-Nike-Dunk-Low-Panda.png',
    price: '$100',
    description: 'Nike Dunk Low Panda',
    product_description:,
  },
  {
    product_name: 'New Balance shoe',
    brand_id: 4,
    filename: '20-Joe-Freshgoods-9060-Penny-Cookie-Pink.png',
    price: '$200',
    description: 'Joe Freshgoods 9060 Penny Cookie Pink',
    product_description:,
  },
  {
    product_name: 'New Balance shoe',
    brand_id: 4,
    filename: '21-FuelCell-4040-v6-Turf-Trainer.png',
    price: '$90',
    description: 'FuelCell 4040 v6 Turf Trainer',
    product_description:,
  },
  {
    product_name: 'New Balance shoe',
    brand_id: 4,
    filename: '22-TWO-WXY-v3.png',
    price: '$120',
    description: 'TWO WXY v3',
    product_description:,
  },
  {
    product_name: 'New Balance shoe',
    brand_id: 4,
    filename: '23-574-Core.png',
    price: '$85',
    description: '574 Core',
    product_description:,
  },
  {
    product_name: 'New Balance shoe',
    brand_id: 4,
    filename: '24-Fresh-Foam-1080v12.png',
    price: '$160',
    description: 'Fresh Foam 1080v12',
    product_description:,
  },
 
];

const seedStyles = () => Style.bulkCreate(styleData);

module.exports = seedStyles;
